import csv
import json
import os
import sys
from datetime import datetime, timezone

# Configuration
DATA_DIR = "public/assets/data/source"
OUTPUT_FILE = "public/assets/data/current_climate_state.json"
TIMESERIES_FILE = os.path.join(DATA_DIR, "gwi_timeseries.csv")
RATES_FILE = os.path.join(DATA_DIR, "gwi_rates.csv")

# Constants
SECONDS_PER_YEAR = 365.2425 * 24 * 60 * 60


# Note that to minimise dependencies, we are not using pandas/etc here.


def parse_csv_headers(filename):
    """
    Parses the two-row header of the CSV to find indices for required columns.
    Returns a dictionary mapping (variable, percentile) -> index.
    """
    with open(filename, 'r') as f:
        reader = csv.reader(f)
        header1 = next(reader)
        header2 = next(reader)

        # We need to handle the fact that the first column is part of the
        # header "block" but represents the row label (Year). The data columns
        # start after that. Row 1 starts with "variable" and Row 2 with
        # "percentile". So index 0 is the label column.

        mapping = {}
        for i, (var, perc) in enumerate(zip(header1, header2)):
            if i == 0:
                continue  # Skip the "Year" column
            mapping[(var, perc)] = i

    return mapping


def get_last_row(filename):
    """Returns the last row of the CSV file."""
    with open(filename, 'r') as f:
        reader = csv.reader(f)
        # Skip headers
        next(reader)
        next(reader)
        # Iterate to end
        last_row = None
        for row in reader:
            if row:  # Skip empty rows
                last_row = row
    return last_row


def is_leap_year(year: int) -> bool:
    return year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)


def midyear_datetime_utc(year: int) -> datetime:
    """
    Return the mid-year moment for an annual-mean value.

    Per the convention described on Wikipedia for "mid-year day":
    - Common years: midpoint is at noon on July 2.
    - Leap years: midpoint is at midnight at the start of July 2.

    We express this in UTC to avoid environment-dependent local time issues.
    """
    if is_leap_year(year):
        return datetime(year, 7, 2, 0, 0, 0, tzinfo=timezone.utc)
    return datetime(year, 7, 2, 12, 0, 0, tzinfo=timezone.utc)


def main():
    print("Starting data processing...")

    # 1. Process Timeseries (Levels)
    print(f"Reading {TIMESERIES_FILE}...")
    ts_mapping = parse_csv_headers(TIMESERIES_FILE)
    ts_last_row = get_last_row(TIMESERIES_FILE)

    if not ts_last_row:
        print("Error: No data found in timeseries file.")
        sys.exit(1)

    last_year = int(ts_last_row[0])
    basis_dt = midyear_datetime_utc(last_year)
    basis_datetime_utc = basis_dt.isoformat().replace("+00:00", "Z")
    basis_date = basis_dt.date().isoformat()
    print(f"Latest Year: {last_year}, Basis Date: {basis_date}, "
          f"Basis Datetime (UTC): {basis_datetime_utc}")

    # 2. Process Rates
    print(f"Reading {RATES_FILE}...")
    rates_mapping = parse_csv_headers(RATES_FILE)
    rates_last_row = get_last_row(RATES_FILE)

    if not rates_last_row:
        print("Error: No data found in rates file.")
        sys.exit(1)

    # 3. Extract Data for Ant (5, 50, 95)
    percentiles = ['5', '50', '95']
    variable = 'Ant'

    anthro_data = {}

    for p in percentiles:
        # Level
        try:
            level_idx = ts_mapping[(variable, p)]
            level_val = float(ts_last_row[level_idx])
        except KeyError:
            print(f"Error: Could not find column for {variable} {p} in timeseries.")
            sys.exit(1)

        # Rate
        try:
            rate_idx = rates_mapping[(variable, p)]
            rate_val_per_year = float(rates_last_row[rate_idx])
            rate_val_per_sec = rate_val_per_year / SECONDS_PER_YEAR
        except KeyError:
            print(f"Error: Could not find column for {variable} {p} in rates.")
            sys.exit(1)

        anthro_data[p] = {
            "level": level_val,
            "rate_per_year": rate_val_per_year, # Keeping this for reference/debugging
            "rate_per_sec": rate_val_per_sec
        }

    # 4. JSON Structure
    output_data = {
        "_comment_generated": (
            "DO NOT EDIT THIS FILE MANUALLY. It is generated during the website build by "
            "scripts/process_data.py from the CSVs in public/assets/data/source/."
        ),
        "_comment_basis_date": (
            "The basis_date / basis_datetime_utc represent the midpoint of the year because the annual "
            "values in the timeseries are single-year averages. We use a leap-year-aware mid-year moment "
            "(common years: July 2 at 12:00 UTC; leap years: July 2 at 00:00 UTC) so the live counter can "
            "update per second from the correct temporal anchor."
        ),
        "basis_date": basis_date,
        "basis_datetime_utc": basis_datetime_utc,
        "anthropogenic_warming": anthro_data,
    }

    # 5. Write to File
    # print(f"Writing output to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w') as f:
        json.dump(output_data, f, indent=4)

    # print("Done.")

if __name__ == "__main__":
    main()
