#! /usr/bin/python3
# Python program for serving the temperature as an API
import flask
import time
import json
import os
import datetime
import requests

app = flask.Flask(__name__)
app.config["DEBUG"] = False

# Path to the data file generated by the build process
DATA_FILE_PATH = '/var/www/html/assets/data/current_climate_state.json'


def get_current_climate_data():
    """Reads the climate data from the JSON file."""
    try:
        # 1. Try absolute Docker path
        if os.path.exists(DATA_FILE_PATH):
            with open(DATA_FILE_PATH, 'r') as f:
                return json.load(f)

        # 2. Try relative path (local dev or alternative Docker setup)
        relative_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            '../public/assets/data/current_climate_state.json')
        if os.path.exists(relative_path):
            with open(relative_path, 'r') as f:
                return json.load(f)

        # 3. Fallback for serverless environments (like Vercel)
        # Fetch dynamically from the same domain's static assets
        json_url = flask.request.host_url.rstrip('/') + '/assets/data/current_climate_state.json'
        resp = requests.get(json_url, timeout=5)
        if resp.status_code == 200:
            return resp.json()

        print(f"Failed to fetch JSON from {json_url} (Status: {resp.status_code})")
        return None

    except Exception as e:
        print(f"Error reading climate data: {e}")
        return None


@app.route('/api')
def api_all():
    data = get_current_climate_data()

    if not data:
        return flask.jsonify({'error': 'Data not available'}), 500

    # Parse basis date
    # basis_datetime_utc is like "2024-07-02T00:00:00Z"
    try:
        basis_dt = datetime.datetime.strptime(
            data['basis_datetime_utc'], "%Y-%m-%dT%H:%M:%SZ")
        # Ensure it is treated as UTC
        basis_dt = basis_dt.replace(tzinfo=datetime.timezone.utc)
        basis_timestamp = basis_dt.timestamp()
    except Exception as e:
        return flask.jsonify({'error': f'Error parsing date: {e}'}), 500

    # Current time
    current_time = time.time()

    # Calculate seconds since basis
    time_since_basis = current_time - basis_timestamp

    # Get rates and levels (using the '50' estimate as the central one)
    # The JSON structure is: "anthropogenic_warming": { "50": { "level": ..., "rate_per_sec": ... } }
    warming_info = data['anthropogenic_warming']['50']
    base_level = warming_info['level']
    rate_per_sec = warming_info['rate_per_sec']

    # Calculate current warming
    current_warming_c = base_level + (rate_per_sec * time_since_basis)
    current_warming_f = current_warming_c * 1.8

    result = [
        {
            'id': 1,
            'title': 'Temperature rise in Celsius',
            'temperature_rise': str(current_warming_c)
        },
        {
            'id': 2,
            'title': 'Temperature rise in Fahrenheit',
            'temperature_rise': str(current_warming_f)
        }
    ]

    return flask.jsonify(result)


if __name__ == '__main__':
    app.run()
